name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run:
          sudo apt update && sudo apt install -y libglu1-mesa-dev freeglut3-dev mesa-common-dev libsoil-dev libglfw3-dev valgrind cppcheck g++-9 gcovr
    - name: make
      run: g++-9 Sources/*.cpp Teams/Sources/*.cpp Grafica/*.cpp *.cpp IO/*.cpp -o main  -g -I/usr/include/GLFW -I/usr/include/SOIL -lglfw -lGL -lSOIL -std=c++14 -Wall -Wextra -pedantic -Weffc++
                --coverage -fprofile-arcs -ftest-coverage -g -O0 -lm
    - name: cppcheck
      run:
        cppcheck --enable=all .
    - name: valgrind
      run:
        valgrind --leak-check=full --show-leak-kinds=all
                 --track-origins=yes --error-exitcode=1 ./main
    - name: coverage
      run: |
        gcov Sources/*.cpp Teams/Sources/AlfaRomeoRacing.cpp Teams/Sources/Haas.cpp Teams/Sources/AlphaTauri.cpp Teams/Sources/McLaren.cpp Teams/Sources/MercedesAMG.cpp Teams/Sources/RacingPoint.cpp Teams/Sources/RedBullRacing.cpp Teams/Sources/Renault.cpp Teams/Sources/ScuderiaFerrari.cpp  Teams/Sources/Williams.cpp
        mkdir cov/
        gcovr -r . --html --html-details -o cov/coverage.html --print-summary
        mv -v cov/  public/
    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        enable_jekyll: true
